version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: gz_raw_data est le nom original du dataset source, raw son alias.
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day}
        columns:
          - name: pdt_id
            description: id of the product sale
            tests:
              - not_null
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of the order
          - name: revenue
            description: price of the product
          - name: quantity
            description: quantity of the same product in the order
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / what products we have and the associated data
        columns:
          - name: products_id
            description: id of the product
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: purchse price of the product
      - name: ship
        identifier: raw_gz_ship
        description: ships of Greenweez / a ship list with orders_id, shipping_fee, ship_cost, etc.
        columns:
          - name: orders_id
            description: id of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: total shipping fee payed by the customer for the order
          - name: logCost
            description: log cost payed by the supplier for the order
          - name: ship_cost
            description: ship cost payed by the supplier for the order