version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per productid found in each orders_id
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
           warn_after: {count: 90, period: day}
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quanitity
             description: the quantity of products purchased for a given order
         tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"

       - name: product
         identifier: raw_gz_product
         description: produst of Greenweez
         columns:
           - name: products_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: purchase_price
             description: the purchase price of the product

       - name: ship
         identifier: raw_gz_ship
         description: shipping data for Greenweez orders
         columns:
           - name: orders_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: log_cost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider    

       - name: adwords
         identifier: raw_gz_adwords
         description: "Données publicitaires Google Adwords."
         columns:
          - name: date_date
            description: "Date de la campagne."
            tests:
              - not_null
          - name: paid_source
            description: "Source publicitaire (Google Adwords)."
            tests:
              - not_null
          - name: campaign_key
            description: "Clé unique de la campagne Adwords."
            tests:
              - not_null
          - name: camPGN_name
            description: "Nom de la campagne."
            tests:
              - not_null
          - name: ads_cost
            description: "Coût des annonces."
            tests:
              - not_null
          - name: impression
            description: "Nombre d'impressions générées par la campagne."
            tests:
              - not_null
          - name: click
            description: "Nombre de clics générés par la campagne."
            tests:
              - not_null

       - name: bing
         identifier: raw_gz_bing
         description: "Données publicitaires Bing."
         columns:
          - name: date_date
            description: "Date de la campagne."
            tests:
              - not_null
          - name: paid_source
            description: "Source publicitaire (Bing)."
            tests:
              - not_null
          - name: campaign_key
            description: "Clé unique de la campagne Bing."
            tests:
              - not_null
          - name: camPGN_name
            description: "Nom de la campagne."
            tests:
              - not_null
          - name: ads_cost
            description: "Coût des annonces."
            tests:
              - not_null
          - name: impression
            description: "Nombre d'impressions générées par la campagne."
            tests:
              - not_null
          - name: click
            description: "Nombre de clics générés par la campagne."
            tests:
              - not_null

       - name: criteo
         identifier: raw_gz_criteo
         description: "Données publicitaires Criteo."
         columns:
          - name: date_date
            description: "Date de la campagne."
            tests:
              - not_null
          - name: paid_source
            description: "Source publicitaire (Criteo)."
            tests:
              - not_null
          - name: campaign_key
            description: "Clé unique de la campagne Criteo."
            tests:
              - not_null
          - name: camPGN_name
            description: "Nom de la campagne."
            tests:
              - not_null
          - name: ads_cost
            description: "Coût des annonces."
            tests:
              - not_null
          - name: impression
            description: "Nombre d'impressions générées par la campagne."
            tests:
              - not_null
          - name: click
            description: "Nombre de clics générés par la campagne."
            tests:
              - not_null

       - name: facebook
         identifier: raw_gz_facebook
         description: "Données publicitaires Facebook."
         columns:
          - name: date_date
            description: "Date de la campagne."
            tests:
              - not_null
          - name: paid_source
            description: "Source publicitaire (Facebook)."
            tests:
              - not_null
          - name: campaign_key
            description: "Clé unique de la campagne Facebook."
            tests:
              - not_null
          - name: camPGN_name
            description: "Nom de la campagne."
            tests:
              - not_null
          - name: ads_cost
            description: "Coût des annonces."
            tests:
              - not_null
          - name: impression
            description: "Nombre d'impressions générées par la campagne."
            tests:
              - not_null
          - name: click
            description: "Nombre de clics générés par la campagne."
            tests:
              - not_null

models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"

   - name: int_campaigns
     description: "Modèle intermédiaire consolidé des données de campagnes publicitaires provenant de différentes sources."
     columns:
      - name: date_date
        description: "Date de la campagne."
        tests:
          - not_null
      - name: paid_source
        description: "Source publicitaire (ex. Facebook, Bing, Criteo, Adwords)."
        tests:
          - not_null
      - name: campaign_key
        description: "Clé unique de la campagne dans la source."
        tests:
          - not_null
      - name: campaign_name
        description: "Nom de la campagne."
        tests:
          - not_null
      - name: ads_cost
        description: "Coût des annonces pour la campagne."
        tests:
          - not_null
      - name: impression
        description: "Nombre d'impressions générées par la campagne."
        tests:
          - not_null
      - name: click
        description: "Nombre de clics générés par la campagne."
        tests:
          - not_null
     tests:
      - unique:
          column_name: (date_date || '_' || paid_source || '_' || campaign_key)

   - name: int_campaigns_day
     description: "Modèle intermédiaire consolidé des campagnes publicitaires, agrégé par jour avec le coût, les impressions et les clics."
     columns:
      - name: date_date
        description: "Date des campagnes publicitaires agrégées."
        tests:
          - not_null
          - unique

      - name: ads_cost
        description: "Coût total des annonces publicitaires pour chaque journée."
        tests:
          - not_null

      - name: ads_impression
        description: "Nombre total d'impressions publicitaires pour chaque journée."
        tests:
          - not_null

      - name: ads_clicks
        description: "Nombre total de clics publicitaires pour chaque journée."
        tests:
          - not_null

   - name: finance_campaigns_day
     description: "Modèle consolidé des campagnes et performances financières journalières, incluant les coûts publicitaires et la marge opérationnelle."
     columns:
      - name: date_date
        description: "Clé primaire. Date de la campagne et des performances financières consolidées."
        tests:
          - not_null
          - unique

      - name: ads_margin
        description: "Marge publicitaire, calculée en soustrayant les coûts publicitaires de la marge opérationnelle."
        tests:
          - not_null

      - name: average_basket
        description: "Panier moyen journalier."
        tests:
          - not_null

      - name: operational_margin
        description: "Marge opérationnelle totale pour la journée."
        tests:
          - not_null

      - name: ads_cost
        description: "Coût total des annonces pour la journée."
        tests:
          - not_null

      - name: ads_impression
        description: "Nombre total d'impressions publicitaires pour la journée."
        tests:
          - not_null

      - name: ads_clicks
        description: "Nombre total de clics publicitaires pour la journée."
        tests:
          - not_null

      - name: quantity
        description: "Quantité totale de produits vendus ou services rendus pour la journée."
        tests:
          - not_null

      - name: revenue
        description: "Revenu total généré pour la journée."
        tests:
          - not_null

      - name: purchase_cost
        description: "Coût total des achats pour la journée."
        tests:
          - not_null

      - name: margin
        description: "Marge totale pour la journée."
        tests:
          - not_null

      - name: shipping_fee
        description: "Total des frais de livraison pour la journée."
        tests:
          - not_null

      - name: logcost
        description: "Total des coûts logistiques pour la journée."
        tests:
          - not_null

      - name: ship_cost
        description: "Coût total d'expédition pour la journée."
        tests:
          - not_null