version: 2

sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per productid found in each orders_id
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
           warn_after: {count: 90, period: day}
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quanitity
             description: the quantity of products purchased for a given order
         tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"

       - name: product
         identifier: raw_gz_product
         description: produst of Greenweez
         columns:
           - name: products_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: purchase_price
             description: the purchase price of the product

       - name: ship
         identifier: raw_gz_ship
         description: shipping data for Greenweez orders
         columns:
           - name: orders_id
             description: Primary key
             tests:
              - unique
              - not_null
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: log_cost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider    

       - name: adwords
         identifier: raw_gz_adwords
         description: "Google Adwords advertising data."
         columns:
          - name: date_date
            description: "Campaign date."
            tests:
             - not_null
          - name: paid_source
            description: "Advertising source (Google Adwords)."
            tests:
            - not_null
          - name: campaign_key
            description: "Unique key for the Adwords campaign."
            tests:
            - not_null
          - name: camPGN_name
            description: "Name of the campaign."
            tests:
            - not_null
          - name: ads_cost
            description: "Cost of the ads."
            tests:
            - not_null
          - name: impression
            description: "Number of impressions generated by the campaign."
            tests:
            - not_null
          - name: click
            description: "Number of clicks generated by the campaign."
            tests:
            - not_null

       - name: bing
         identifier: raw_gz_bing
         description: "Bing advertising data."
         columns:
         - name: date_date
           description: "Campaign date."
           tests:
            - not_null
         - name: paid_source
           description: "Advertising source (Bing)."
           tests:
           - not_null
         - name: campaign_key
           description: "Unique key for the Bing campaign."
           tests:
           - not_null
         - name: camPGN_name
           description: "Name of the campaign."
           tests:
           - not_null
         - name: ads_cost
           description: "Cost of the ads."
           tests:
           - not_null
         - name: impression
           description: "Number of impressions generated by the campaign."
           tests:
           - not_null
         - name: click
           description: "Number of clicks generated by the campaign."
           tests:
           - not_null

       - name: criteo
         identifier: raw_gz_criteo
         description: "Criteo advertising data."
         columns:
         - name: date_date
           description: "Campaign date."
           tests:
           - not_null
         - name: paid_source
           description: "Advertising source (Criteo)."
           tests:
           - not_null
         - name: campaign_key
           description: "Unique key for the Criteo campaign."
           tests:
           - not_null
         - name: camPGN_name
           description: "Name of the campaign."
           tests:
           - not_null
         - name: ads_cost
           description: "Cost of the ads."
           tests:
           - not_null
         - name: impression
           description: "Number of impressions generated by the campaign."
           tests:
           - not_null
         - name: click
           description: "Number of clicks generated by the campaign."
           tests:
           - not_null

       - name: facebook
         identifier: raw_gz_facebook
         description: "Facebook advertising data."
         columns:
         - name: date_date
           description: "Campaign date."
           tests:
           - not_null
         - name: paid_source
           description: "Advertising source (Facebook)."
           tests:
           - not_null
         - name: campaign_key
           description: "Unique key for the Facebook campaign."
           tests:
           - not_null
         - name: camPGN_name
           description: "Name of the campaign."
           tests:
           - not_null
         - name: ads_cost
           description: "Cost of the ads."
           tests:
           - not_null
         - name: impression
           description: "Number of impressions generated by the campaign."
           tests:
           - not_null
         - name: click
           description: "Number of clicks generated by the campaign."
           tests:
           - not_null


models:
   - name: int_sales_margin
     description: "Intermediate model calculating sales margins with purchase cost and margin percent."
     columns:
       - name: products_id
         description: "Unique identifier for each product."
       - name: date_date
         description: "Date of the sale transaction."
       - name: orders_id
         description: "Unique identifier for each order."
       - name: revenue
         description: "Total revenue generated from the sale."
       - name: quantity
         description: "Total quantity sold for each product in the order."
       - name: purchase_price
         description: "Purchase price per unit of the product."
       - name: purchase_cost
         description: "Total purchase cost calculated as Quantity * Purchase_price."
       - name: margin
         description: "Calculated margin as Revenue - Purchase_cost."
       - name: margin_percent
         description: "Percentage margin calculated as (Margin / Revenue) * 100."
     tests:
     - unique:
        column_name: "(orders_id || '-' || products_id)"

   - name: int_campaigns
     description: "Intermediate model consolidating advertising campaign data from different sources."
     columns:
      - name: date_date
        description: "Campaign date."
        tests:
          - not_null
      - name: paid_source
        description: "Advertising source (e.g., Facebook, Bing, Criteo, Adwords)."
        tests:
          - not_null
      - name: campaign_key
        description: "Unique campaign key in the source."
        tests:
          - not_null
      - name: campaign_name
        description:  "Campaign name."
      - name: ads_cost
        description: "Cost of ads for the campaign."
        tests:
          - not_null
      - name: impression
        description:  "Number of impressions generated by the campaign."
        tests:
          - not_null
      - name: click
        description: "Number of clicks generated by the campaign."
        tests:
          - not_null
     tests:
      - unique:
          column_name: (date_date || '_' || paid_source || '_' || campaign_key)

   - name: int_campaigns_day  
     description: "Intermediate model consolidating advertising campaigns, aggregated by day with cost, impressions, and clicks."
     columns:
     - name: date_date
       description: "Date of aggregated advertising campaigns."
     - name: ads_cost
       description: "Total cost of advertising for each day."
     - name: ads_impression
       description: "Total number of advertising impressions for each day."
     - name: ads_clicks
       description: "Total number of advertising clicks for each day."

   - name: int_orders_margin
     description: "Intermediate table for order margin calculations"
     columns:
     - name: orders_id
       description: "Unique identifier for each order."
       tests:
       - not_null
     - name: date_date
       description: "Date of the order."
       tests:
       - not_null
     - name: revenue
       description: "Total revenue for the order, rounded to two decimal places."
       tests:
       - not_null
     - name: quantity
       description: "Total quantity of items in the order, rounded to two decimal places."
       tests:
       - not_null
     - name: purchase_cost
       description: "Total purchase cost for the order, calculated as sum of product purchase prices, rounded to two decimal places."
     - name: margin
       description: "Total margin for the order, calculated as revenue - purchase_cost, rounded to two decimal places."

   - name: int_orders_operational
     description: "Intermediate table for operational order data"
     columns:
     - name: orders_id
       description: "Unique identifier for each order."
       tests:
       - not_null
     - name: date_date
       description: "Date of the order."
       tests:
       - not_null
     - name: revenue
       description: "Total revenue for the order."
     - name: quantity
       description: "Total quantity of items in the order."
     - name: purchase_cost
       description: "Total purchase cost of items in the order."
     - name: margin
       description: "Margin for the order, calculated as revenue - purchase_cost."
     - name: shipping_fee
       description: "Total shipping fee for the order."
     - name: logcost
       description: "Logistical cost associated with the order."
     - name: ship_cost
       description: "Shipping cost associated with the order."
     - name: operational_margin
       description: "Operational margin for the order, calculated as margin - (logcost + ship_cost)."

   - name: finance_campaigns_day
     description: "Consolidated model of daily campaign and financial performance, including advertising costs and operational margin."
     columns:
     - name: date_date
       description: "Primary key. Date of the campaign and consolidated financial performance."
       tests:
       - not_null
       - unique
     - name: ads_margin
       description: "Advertising margin, calculated by subtracting advertising costs from the operational margin."
       tests:
       - not_null
     - name: average_basket
       description: "Daily average basket value."
       tests:
       - not_null
     - name: operational_margin
       description: "Total operational margin for the day."
       tests:
       - not_null
     - name: ads_cost
       description: "Total cost of ads for the day."
       tests:
       - not_null
     - name: ads_impression
       description: "Total number of ad impressions for the day."
       tests:
       - not_null
     - name: ads_clicks
       description: "Total number of ad clicks for the day."
       tests:
       - not_null
     - name: quantity
       description: "Total quantity of products sold or services rendered for the day."
       tests:
       - not_null
     - name: revenue
       description: "Total revenue generated for the day."
       tests:
       - not_null
     - name: purchase_cost
       description: "Total purchase cost for the day."
       tests:
       - not_null
     - name: margin
       description: "Total margin for the day."
       tests:
       - not_null
     - name: shipping_fee
       description: "Total shipping fees for the day."
       tests:
       - not_null
     - name: logcost
       description: "Total logistical costs for the day."
       tests:
       - not_null
     - name: ship_cost
       description: "Total shipping cost for the day."
       tests:
       - not_null

   - name: finance_campaigns_month
     description: "Finance table for monthly campaign analysis"
     columns:
     - name: datemonth
       description: "Month identifier for the aggregated monthly data."
       tests:
       - not_null
       - unique
     - name: ads_margin
       description: "Total advertising margin for the month."
       tests:
       - not_null
     - name: average_basket
       description: "Average basket value for the month."
       tests:
       - not_null
     - name: operational_margin
       description: "Total operational margin for the month."
       tests:
       - not_null
     - name: ads_cost
       description: "Total cost of ads for the month."
       tests:
       - not_null
     - name: ads_impression
       description: "Total number of ad impressions for the month."
       tests:
       - not_null
     - name: ads_clicks
       description: "Total number of ad clicks for the month."
       tests:
       - not_null
     - name: quantity
       description: "Total quantity of products sold or services rendered for the month."
       tests:
       - not_null
     - name: revenue
       description: "Total revenue generated for the month."
       tests:
       - not_null
     - name: purchase_cost
       description: "Total purchase cost for the month."
       tests:
       - not_null
     - name: margin
       description: "Total margin for the month."
       tests:
       - not_null
     - name: shipping_fee
       description: "Total shipping fees for the month."
       tests:
       - not_null
     - name: logcost
       description: "Total logistical costs for the month."
       tests:
       - not_null
     - name: ship_cost
       description: "Total shipping cost for the month."
       tests:
       - not_null

   - name: finance_days
     description: "Finance table for daily financial metrics"
     columns:
     - name: date_date
       description: "Date of the financial metrics."
       tests:
       - not_null
       - unique
     - name: nb_transactions
       description: "Number of transactions for the day."
       tests:
       - not_null
     - name: revenue
       description: "Total revenue for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: average_basket
       description: "Average basket value for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: margin
       description: "Total margin for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: operational_margin
       description: "Total operational margin for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: purchase_cost
       description: "Total purchase cost for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: shipping_fee
       description: "Total shipping fees for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: logcost
       description: "Total logistical costs for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: ship_cost
       description: "Total shipping cost for the day, rounded to two decimal places."
       tests:
       - not_null
     - name: quantity
       description: "Total quantity of products sold or services rendered for the day."
       tests:
       - not_null